FROM golang:1.10.3-alpine3.7
COPY . /go/src/github.com/smallinsky/grpc-echo
RUN go install github.com/smallinsky/grpc-echo/echo-client

FROM alpine:3.7
COPY --from=0 /go/bin/echo-client /echo-client
COPY cert /cert
CMD ["/echo-client"]
