apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-client
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: echo-client
        type: app
    spec:
      containers:
      - env:
        - name: COS
          value: bar
        image: msmallinsky/echo-client:bdc164c
        imagePullPolicy: Always
        name: echo-client
